export enum NotifType {
	NEW_FOLLOWER = 'new_follower',
	POST_REACTION = 'post_reaction',
	COMMENT_REACTION = 'comment_reaction',
	POST_COMMENT = 'post_comment',
	COMMENT_REPLY = 'comment_reply',
	MENTION = 'mention',
	NEW_QUOTATION = 'new_quotation',
	QUOTATION_ACCEPTED = 'quotation_accepted',
	QUOTATION_REJECTED = 'quotation_rejected',
	ORDER_CONFIRMED = 'order_confirmed',
	ORDER_COMPLETED = 'order_completed',
	ORDER_DISPUTED = 'order_disputed',
	NEW_MESSAGE = 'new_message',
	VERIFICATION_APPROVED = 'verification_approved',
	VERIFICATION_REJECTED = 'verification_rejected',
	SUBSCRIPTION_EXPIRING = 'subscription_expiring',
	QR_QUOTA_WARNING = 'qr_quota_warning',
	CERTIFICATION_EXPIRING = 'certification_expiring',
	SYSTEM_ANNOUNCEMENT = 'system_announcement',
	CHARITY_DONATION_RECEIVED = 'charity_donation_received',
	REVIEW_RECEIVED = 'review_received',
	REPORT_ACTIONED = 'report_actioned',
}
