export enum ErrorCode {
	INTERNAL_SERVER_ERROR = 'Internal server error',
	UNAUTHORIZED = 'Unauthorized',
	INVALID_PERMISSION = 'Invalid permission',
	INCORRECT_EMAIL_PASSWORD = 'Incorrect email or password',
	USER_NOT_FOUND = 'User not found',
	PROFILE_NOT_FOUND = 'Profile not found',
	CANNOT_UPDATE_OTHERS_PROFILE = 'You can only update your own profile',
	EMAIL_EXISTS = 'Email already exists',
	USER_EXIST = 'User already exists',
	NOT_PERMITTED_ROLE = 'Not permitted role',
	USER_IN_ACTIVE = 'User in active',
	INCORRECT_CURRENT_PASSWORD = 'Incorrect current password',
	INVALID_OTP = 'Invalid OTP',
	EMAIL_NOT_FOUND = 'Email not found',
	PHONE_NOT_FOUND = 'Phone number not found',
	SESSION_NOT_FOUND = 'Session does not exist',
	PHONE_OR_EMAIL_REQUIRED = 'Phone or email is required',
	INCORRECT_LOGIN_INFO = 'Login information is incorrect',
	LOGIN_ACCOUNT_LOCKED = 'Account temporarily locked due to multiple failed login attempts',
	PASSWORD_REUSE_NOT_ALLOWED = 'Cannot reuse recent passwords',

	STATE_NOT_FOUND = 'State not found',
	CITY_NOT_FOUND = 'City not found',
	CATEGORY_NOT_FOUND = 'Category not found',
	CATEGORY_SLUG_EXISTS = 'Category slug already exists',
	CATEGORY_PARENT_INVALID = 'Cannot set parentId to its own id',
	CATEGORY_HAS_PRODUCTS = 'Cannot hide category with existing products',
	CATEGORY_HAS_CHILDREN = 'Cannot hide category with children sub-categories',
	SPORT_NOT_FOUND = 'Sport not found',
	SEASON_NOT_FOUND = 'Season not found',
	CROP_SEASON_INVALID_DATES = 'Start date must be before expected harvest date',
	CROP_SEASON_INVALID_ACTUAL_HARVEST_DATE = 'Actual harvest date cannot be earlier than start date',
	CROP_SEASON_CANNOT_UPDATE_TERMINAL_STATE = 'Cannot update a harvested or cancelled crop season',
	CROP_SEASON_INVALID_STATE_TRANSITION = 'Invalid state transition for crop season',
	CROP_SEASON_DELETE_DENIED_HAS_DATA = 'Cannot delete crop season because it has associated production logs or batches',
	CROP_SEASON_AREA_EXCEEDS_FARM_AREA = 'Crop season area cannot exceed the total farm area',
	GREEN_PROFILE_NOT_FOUND = 'Green profile not found',
	GREEN_PROFILE_NOT_OWNED = 'You do not own this green profile',
	USER_ALREADY_HAS_GREEN_PROFILE = 'Green profile already exists',
	ORGANIZATION_ALREADY_HAS_GREEN_PROFILE = 'Organization already has a green profile',
	ORGANIZATION_NOT_MEMBER = 'You are not a member of this organization',
	SCHOOL_DISTRICT_NOT_FOUND = 'School district not found',
	SCHOOL_NOT_FOUND = 'School not found',
	BOOSTER_NOT_FOUND = 'Booster not found',
	EVENT_NOT_FOUND = 'Event not found',
	CERTIFICATION_NOT_FOUND = 'One or more certifications were not found',
	PRODUCT_NOT_FOUND = 'Product not found',
	PRODUCT_FORBIDDEN = 'You can only modify your own products',
	PRODUCT_UNAVAILABLE = 'Product unavailable',
	PRODUCT_ALREADY_EXISTS = 'Product with the same name already exists in this category',
	PHONE_ALREADY_EXISTS = 'Phone already exists',
	ORDER_NOT_FOUND = 'Order not found',
	ORDER_ITEM_NOT_FOUND = 'Order item not found',
	WORKER_ALREADY_ADDED_TO_EVENT = 'Worker already added to event',
	WORKER_NOT_FOUND_IN_EVENT = 'Worker not found in event',
	ORGANIZATION_ALREADY_VERIFIED = 'Organization is already verified',
	ORGANIZATION_ALREADY_HAS_PENDING_VERIFICATION_REQUEST = 'Organization already has a pending verification request',
	ONLY_ORGANIZATION_ADMINS_CAN_SUBMIT_VERIFICATION_REQUESTS = 'Only organization admins can submit verification requests',
	VERIFICATION_REQUEST_NOT_FOUND = 'Verification request not found',
	ORGANIZATION_VERIFICATION_REJECTED = 'Organization verification rejected',
	ORGANIZATION_NOT_FOUND = 'Organization not found',
	ORGANIZATION_MEMBER_LIMIT_REACHED = 'Organization member limit reached',
	MEMBER_NOT_FOUND_IN_ORGANIZATION = 'Member not found in organization',
	USER_ALREADY_MEMBER_OR_INVITED = 'User is already a member or invited to this organization',
	CANNOT_DEMOTE_LAST_ADMIN = 'Cannot demote the last organization admin',
	CANNOT_DEACTIVATE_LAST_ADMIN = 'Cannot deactivate the last organization admin',
	CANNOT_REMOVE_LAST_ADMIN = 'Cannot remove the last organization admin',
	MEMBER_MUST_ACCEPT_INVITE = 'Member must accept the invitation before becoming active',
	INVALID_INVITE_TOKEN = 'Invalid invite token',
	INVITATION_NOT_FOUND_OR_ALREADY_ACCEPTED = 'Invitation not found or already accepted',
	ONLY_ACTIVE_ADMINS_CAN_PERFORM_THIS_ACTION = 'Only active organization admins can perform this action',
	VERIFICATION_REQUEST_NOT_PENDING = 'Verification request is not in pending status',
	UNAUTHORIZED_ACCEPT_INVITATION = 'You are not authorized to accept this invitation',
	UNAUTHORIZED_DECLINE_INVITATION = 'You are not authorized to decline this invitation',

	// CURRENT_PASSWORD_NOT_MATCH = 'Current password does not match',
	NEW_PASSWORD_NOT_MATCH = 'New password does not match',
	NEW_PASSWORD_SAME_AS_CURRENT = 'New password must be different from the current password',
	// OTP_INVALID = 'OTP is incorrect',
	OTP_EXPIRED_OR_NOT_FOUND = 'OTP has expired, please request a new one',
	OTP_MAX_ATTEMPTS_EXCEEDED = 'You have entered the wrong OTP too many times',
	OTP_DAILY_LIMIT_EXCEEDED = 'You have exceeded the daily limit for sending OTP',
	OTP_COOLDOWN_ACTIVE = 'Please wait 60 seconds before requesting a new OTP',
	EMAIL_VERIFICATION_LINK_INVALID = 'Verification link is invalid or expired',

	POST_NOT_FOUND = 'Post not found',
	POST_FORBIDDEN = 'You can only modify your own posts',
	POST_BODY_OR_MEDIA_REQUIRED = 'Post must have body text or at least one image',
	POST_MEDIA_NOT_FOUND = 'One or more media files were not found',
	POST_MEDIA_NOT_OWNED = 'You can only attach media you uploaded',
	POST_MEDIA_LIMIT_EXCEEDED = 'Too many images attached to this post',
	POST_MEDIA_INVALID_TYPE = 'Only image media is supported for posts',
	POST_INVALID_TAG = 'Invalid post tag',
	POST_HASHTAG_LIMIT_EXCEEDED = 'Too many hashtags in post body',

	MEDIA_NOT_FOUND = 'Media file not found',
	MEDIA_NOT_OWNED = 'You can only use media you uploaded',
	MEDIA_INVALID_PURPOSE = 'Invalid media upload purpose',
	MEDIA_INVALID_TYPE = 'File type is not allowed for this upload',
	MEDIA_FILE_TOO_LARGE = 'File exceeds the maximum allowed size',
	MEDIA_NOT_READY = 'Media file is not ready yet',
	MEDIA_ALREADY_READY = 'Media file has already been uploaded',
	MEDIA_UPLOAD_NOT_FOUND = 'Uploaded file was not found in storage',
	MEDIA_UPLOAD_SIZE_EXCEEDED = 'Uploaded file is larger than declared size',
	MEDIA_UPLOAD_INVALID_CONTENT_TYPE = 'Uploaded file content type is not allowed',
	MEDIA_LOCAL_UPLOAD_ONLY = 'Direct file upload is only available when FILE_DRIVER=local',
	MEDIA_INVALID_FOR_AVATAR = 'This media cannot be used as an avatar',
	MEDIA_INVALID_FOR_COVER = 'This media cannot be used as a cover photo',
	MEDIA_INVALID_FOR_POST = 'This media cannot be attached to a post',
	MEDIA_INVALID_FOR_PRODUCTION_LOG = 'This media cannot be attached to a production log',
	MEDIA_INVALID_FOR_PRODUCT = 'This media cannot be attached to a product',
	MEDIA_INVALID_FOR_GREEN_PROFILE_PHOTO = 'This media cannot be used for green profile photo',
	MEDIA_INVALID_FOR_GREEN_PROFILE_VIDEO = 'This media cannot be used for green profile video',

	ADMIN_CANNOT_ACT_ON_SELF = 'An admin cannot perform this action on their own account',
	ADMIN_CANNOT_ASSIGN_ADMIN_ROLE = 'Admin role cannot be assigned through this endpoint',
	ADMIN_CANNOT_CHANGE_ROLE_OF_ADMIN = 'Cannot change the role of another admin account',

	CANNOT_BLOCK_SELF = 'You cannot block yourself',
	USER_ALREADY_BLOCKED = 'User is already blocked',
	BLOCK_NOT_FOUND = 'Block not found',

	POST_ALREADY_SHARED = 'You have already reposted this post',

	COMMENT_NOT_FOUND = 'Comment not found',
	COMMENT_PARENT_NOT_BELONG_TO_POST = 'Comment parent not belong to post',
	COMMENT_FORBIDDEN = 'You do not have permission to update or delete this comment',
	COMMENT_CANNOT_REPLY_TO_REPLY = 'Cannot reply to a reply comment',
	REACTION_NOT_FOUND = 'Reaction not found',
	CROP_SEASON_OVERLAPPING = 'Crop season dates overlap with an existing crop season for the same green profile',
	PRODUCTION_LOG_MEDIA_NOT_FOUND = 'One or more media files were not found or not owned by you',
	PRODUCTION_LOG_CANNOT_ADD_TO_TERMINAL_STATE = 'Cannot add a production log to a harvested or cancelled crop season',
	PRODUCTION_LOG_INVALID_DATE_FUTURE = 'Production log date cannot be in the future',
	PRODUCTION_LOG_INVALID_DATE_BEFORE_START = 'Production log date cannot be earlier than the crop season start date',

	FOLLOW_SELF = 'You cannot follow yourself',
	USER_ALREADY_FOLLOWED = 'You are already following this user',
	FOLLOW_REQUEST_ALREADY_PENDING = 'The request to follow is already pending',
	ORGANIZATION_ALREADY_FOLLOWED = 'You are already following this organization',
	FOLLOWEE_NOT_FOUND = 'Followee not found',
	FOLLOW_NOT_FOUND = 'Follow not found',
	FOLLOW_ALREADY_ACTIVE = 'Follow request has already been accepted',
	FOLLOW_NOT_PENDING = 'Follow is not pending',
	PRODUCTION_LOG_NOT_FOUND = 'Production log not found',

	CERTIFICATION_ISSUE_DATE_FUTURE = 'Certification issue date cannot be in the future',
	CERTIFICATION_INVALID_DATE_RANGE = 'Certification issue date must be before expiry date',
	CERTIFICATION_EXPIRED_OR_REVOKED = 'One or more certifications are expired or revoked',
	CERTIFICATION_ALREADY_REVIEWED = 'This certification has already been reviewed',
	CERTIFICATION_REJECT_REQUIRES_NOTE = 'Admin note is required when rejecting a certification',
	BATCH_CODE_ALREADY_EXISTS = 'Batch code already exists',
	BATCH_NOT_FOUND = 'Batch not found',
	BATCH_UPDATE_DENIED_TERMINAL_STATE = 'Cannot update batch in shipped, sold, or recalled state',
	BATCH_INVALID_STATE_TRANSITION = 'Invalid state transition for batch',
	BATCH_INVALID_HARVEST_DATE = 'Harvest date cannot be in the future or before crop season start date',
	BATCH_CODE_UPDATE_DENIED_AFTER_QR = 'Cannot update batch code after QR code is generated',
	CANNOT_CREATE_BATCH_FOR_ARCHIVED_OR_DRAFT_PRODUCT = 'Cannot create batch for an archived or draft product',
	CROP_SEASON_CANCELLED = 'Cannot create batch for a cancelled crop season',
	CROP_SEASON_PRODUCT_MISMATCH = 'Crop season does not match the requested product',
	QR_QUOTA_EXCEEDED = 'QR code generation quota exceeded',

	NOTIFICATION_NOT_FOUND = 'Notification not found',
	NOTIFICATION_FORBIDDEN = 'You do not have permission to do it',

	TRACE_TOKEN_NOT_FOUND = 'Trace token not found',
	CANNOT_REPORT_SELF = 'You cannot report yourself',
	REPORT_ALREADY_EXISTS = 'You have already reported this item and it is pending review',

	CANNOT_MESSAGE_SELF = 'You cannot message yourself',
	INVALID_MESSAGE_CONTENT = 'Invalid message content',
	CONVERSATION_NOT_FOUND = 'Conversation not found',
	NOT_CONVERSATION_MEMBER = 'You are not belong to this conversation',

	PRODUCT_REVIEW_ALREADY_EXISTS = 'You have already reviewed this token',
	CANNOT_REVIEW_OWN_PRODUCT = 'You cannot review your own product',

	INVALID_CURSOR = 'Invalid cursor',
	UNSUPPORTED_SEARCH_TYPE = 'Unsupported search type',

	TRADE_POST_NOT_FOUND = 'Trade post not found',
	TRADE_POST_FORBIDDEN = 'You do not own this trade post',
	TRADE_POST_ROLE_FORBIDDEN = 'Your account role is not allowed to perform this action',
	TRADE_POST_CANNOT_MODIFY = 'Cannot modify a closed or expired trade post',

	REPORT_NOT_FOUND = 'Report not found',
	REPORT_INVALID_ACTION_FOR_TARGET = 'This action is not valid for the given report target type',
	APP_VERSION_NOT_FOUND = 'App version not found',
	APP_VERSION_ALREADY_EXISTS = 'An app version record for this platform and version already exists',

	VSX247_USER_INACTIVE = 'The VietGreenX user account is inactive and cannot receive VietShopX247 shares',
	VSX247_CLICK_INVALID_POST = 'Click tracking is only supported for VietShopX247-sourced posts',

	PLAN_REQUIRED = 'Your current plan does not support this feature. Please upgrade to continue.',
	PLAN_NOT_FOUND = 'Membership plan record not found',
	MEMBERSHIP_TIER_ALREADY_EXISTS = 'A membership tier for this plan already exists',

	TWO_FACTOR_NOT_SETUP = 'Two-factor authentication has not been set up',
	TWO_FACTOR_ALREADY_ENABLED = 'Two-factor authentication is already enabled',
	TWO_FACTOR_NOT_ENABLED = 'Two-factor authentication is not enabled',
	TWO_FACTOR_INVALID_CODE = 'Invalid two-factor authentication code',
	TWO_FACTOR_INVALID_BACKUP_CODE = 'Invalid backup code',
	TWO_FACTOR_INVALID_TEMP_TOKEN = 'Invalid or expired temporary token',
	TWO_FACTOR_SETUP_ALREADY_IN_PROGRESS = 'A 2FA setup is already in progress. Call reset-setup to start over.',

	QUOTATION_NOT_FOUND = 'Quotation not found',
	QUOTATION_FORBIDDEN = 'You do not have permission to perform this action on this quotation',
	QUOTATION_NOT_PENDING = 'Quotation is no longer in pending status',
	QUOTATION_CANNOT_SEND_TO_SELF = 'You cannot send a quotation to yourself',
	QUOTATION_ALREADY_SENT = 'You have already sent a pending quotation for this trade post',

	SUPPLIER_REVIEW_NOT_FOUND = 'Supplier review not found',
	SUPPLIER_REVIEW_ALREADY_EXISTS = 'You have already reviewed this supplier',
	SUPPLIER_REVIEW_NO_COMPLETED_ORDER = 'You can only review a supplier after a completed transaction',
	SUPPLIER_REVIEW_FORBIDDEN = 'You do not have permission to modify this review',
	SAVED_SUPPLIER_NOT_FOUND = 'Saved supplier not found',
	SAVED_SUPPLIER_ALREADY_EXISTS = 'You have already saved this supplier',
	CANNOT_SAVE_SELF = 'You cannot save yourself as a supplier',
}
