import { MigrationInterface, QueryRunner } from "typeorm";

export class AddAdminNoteToCertifications1784614568600 implements MigrationInterface {
    name = 'AddAdminNoteToCertifications1784614568600'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "media"."media" DROP CONSTRAINT "fk_media_uploader"`);
        await queryRunner.query(`ALTER TABLE "identity"."profiles" DROP CONSTRAINT "fk_profile_avatar"`);
        await queryRunner.query(`ALTER TABLE "identity"."profiles" DROP CONSTRAINT "fk_profile_cover"`);
        await queryRunner.query(`ALTER TABLE "identity"."profiles" DROP CONSTRAINT "fk_profiles_user"`);
        await queryRunner.query(`ALTER TABLE "system"."maintenance_windows" DROP CONSTRAINT "fk_mw_creator"`);
        await queryRunner.query(`ALTER TABLE "system"."maintenance_windows" DROP CONSTRAINT "fk_mw_updater"`);
        await queryRunner.query(`ALTER TABLE "system"."app_versions" DROP CONSTRAINT "fk_app_version_creator"`);
        await queryRunner.query(`ALTER TABLE "social_graph"."blocks" DROP CONSTRAINT "fk_block_blocked"`);
        await queryRunner.query(`ALTER TABLE "social_graph"."blocks" DROP CONSTRAINT "fk_block_blocker"`);
        await queryRunner.query(`ALTER TABLE "identity"."organizations" DROP CONSTRAINT "fk_org_cover"`);
        await queryRunner.query(`ALTER TABLE "identity"."organizations" DROP CONSTRAINT "fk_org_logo"`);
        await queryRunner.query(`ALTER TABLE "identity"."organizations" DROP CONSTRAINT "fk_org_owner"`);
        await queryRunner.query(`ALTER TABLE "social_graph"."follows" DROP CONSTRAINT "fk_follow_followee_org"`);
        await queryRunner.query(`ALTER TABLE "social_graph"."follows" DROP CONSTRAINT "fk_follow_followee_user"`);
        await queryRunner.query(`ALTER TABLE "social_graph"."follows" DROP CONSTRAINT "fk_follow_follower"`);
        await queryRunner.query(`ALTER TABLE "notification"."notifications" DROP CONSTRAINT "fk_notif_actor"`);
        await queryRunner.query(`ALTER TABLE "notification"."notifications" DROP CONSTRAINT "fk_notif_recipient"`);
        await queryRunner.query(`ALTER TABLE "moderation"."media_moderation_flags" DROP CONSTRAINT "media_moderation_flags_media_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "moderation"."reports" DROP CONSTRAINT "fk_report_actioned_by"`);
        await queryRunner.query(`ALTER TABLE "moderation"."reports" DROP CONSTRAINT "fk_report_reporter"`);
        await queryRunner.query(`ALTER TABLE "moderation"."media_hashes" DROP CONSTRAINT "media_hashes_media_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "messaging"."messages" DROP CONSTRAINT "fk_msg_conversation"`);
        await queryRunner.query(`ALTER TABLE "messaging"."messages" DROP CONSTRAINT "fk_msg_media"`);
        await queryRunner.query(`ALTER TABLE "messaging"."messages" DROP CONSTRAINT "fk_msg_sender"`);
        await queryRunner.query(`ALTER TABLE "messaging"."conversation_members" DROP CONSTRAINT "fk_cm_conversation"`);
        await queryRunner.query(`ALTER TABLE "messaging"."conversation_members" DROP CONSTRAINT "fk_cm_user"`);
        await queryRunner.query(`ALTER TABLE "identity"."verification_requests" DROP CONSTRAINT "fk_verif_org"`);
        await queryRunner.query(`ALTER TABLE "identity"."verification_requests" DROP CONSTRAINT "fk_verif_reviewer"`);
        await queryRunner.query(`ALTER TABLE "identity"."verification_requests" DROP CONSTRAINT "fk_verif_user"`);
        await queryRunner.query(`ALTER TABLE "identity"."user_settings" DROP CONSTRAINT "fk_settings_user"`);
        await queryRunner.query(`ALTER TABLE "identity"."user_sessions" DROP CONSTRAINT "fk_session_user"`);
        await queryRunner.query(`ALTER TABLE "identity"."rbac_role_permissions" DROP CONSTRAINT "fk_rp_perm"`);
        await queryRunner.query(`ALTER TABLE "identity"."rbac_role_permissions" DROP CONSTRAINT "fk_rp_role"`);
        await queryRunner.query(`ALTER TABLE "identity"."organization_members" DROP CONSTRAINT "fk_org_member_inviter"`);
        await queryRunner.query(`ALTER TABLE "identity"."organization_members" DROP CONSTRAINT "fk_org_member_org"`);
        await queryRunner.query(`ALTER TABLE "identity"."organization_members" DROP CONSTRAINT "fk_org_member_user"`);
        await queryRunner.query(`ALTER TABLE "identity"."fcm_devices" DROP CONSTRAINT "fk_fcm_user"`);
        await queryRunner.query(`ALTER TABLE "content"."post_media" DROP CONSTRAINT "fk_pm_media"`);
        await queryRunner.query(`ALTER TABLE "content"."post_media" DROP CONSTRAINT "fk_pm_post"`);
        await queryRunner.query(`ALTER TABLE "content"."post_hashtags" DROP CONSTRAINT "fk_ph_hashtag"`);
        await queryRunner.query(`ALTER TABLE "content"."post_hashtags" DROP CONSTRAINT "fk_ph_post"`);
        await queryRunner.query(`ALTER TABLE "content"."post_tags" DROP CONSTRAINT "fk_pt_post"`);
        await queryRunner.query(`ALTER TABLE "content"."posts" DROP CONSTRAINT "fk_post_author"`);
        await queryRunner.query(`ALTER TABLE "content"."posts" DROP CONSTRAINT "fk_post_org"`);
        await queryRunner.query(`ALTER TABLE "engagement"."shares" DROP CONSTRAINT "fk_share_post"`);
        await queryRunner.query(`ALTER TABLE "engagement"."shares" DROP CONSTRAINT "fk_share_user"`);
        await queryRunner.query(`ALTER TABLE "engagement"."reactions" DROP CONSTRAINT "fk_reaction_user"`);
        await queryRunner.query(`ALTER TABLE "engagement"."comments" DROP CONSTRAINT "comments_reply_to_comment_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "engagement"."comments" DROP CONSTRAINT "comments_reply_to_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "engagement"."comments" DROP CONSTRAINT "fk_comment_author"`);
        await queryRunner.query(`ALTER TABLE "engagement"."comments" DROP CONSTRAINT "fk_comment_parent_comment"`);
        await queryRunner.query(`ALTER TABLE "engagement"."comments" DROP CONSTRAINT "fk_comment_post"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."certifications" DROP CONSTRAINT "fk_cert_gp"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."green_profiles" DROP CONSTRAINT "fk_gp_avatar"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."green_profiles" DROP CONSTRAINT "fk_gp_org"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."green_profiles" DROP CONSTRAINT "fk_gp_user"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."categories" DROP CONSTRAINT "fk_cat_parent"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."products" DROP CONSTRAINT "fk_product_category"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."products" DROP CONSTRAINT "fk_product_gp"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."products" DROP CONSTRAINT "fk_product_org"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."products" DROP CONSTRAINT "fk_product_owner"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."trade_posts" DROP CONSTRAINT "fk_tp_category"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."trade_posts" DROP CONSTRAINT "fk_tp_org"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."trade_posts" DROP CONSTRAINT "fk_tp_product"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."trade_posts" DROP CONSTRAINT "fk_tp_user"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."quotations" DROP CONSTRAINT "fk_quote_product"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."quotations" DROP CONSTRAINT "fk_quote_receiver"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."quotations" DROP CONSTRAINT "fk_quote_sender"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."quotations" DROP CONSTRAINT "fk_quote_trade_post"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."crop_seasons" DROP CONSTRAINT "fk_cs_creator"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."crop_seasons" DROP CONSTRAINT "fk_cs_gp"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."crop_seasons" DROP CONSTRAINT "fk_cs_org"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."crop_seasons" DROP CONSTRAINT "fk_cs_prod"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."batches" DROP CONSTRAINT "fk_batch_creator"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."batches" DROP CONSTRAINT "fk_batch_gp"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."batches" DROP CONSTRAINT "fk_batch_product"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."batches" DROP CONSTRAINT "fk_batch_season"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."public_trace_tokens" DROP CONSTRAINT "fk_trace_batch"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."public_trace_tokens" DROP CONSTRAINT "fk_trace_creator"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."public_trace_tokens" DROP CONSTRAINT "fk_trace_product"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_scans" DROP CONSTRAINT "fk_scan_token"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_quota_tracking" DROP CONSTRAINT "fk_quota_org"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_quota_tracking" DROP CONSTRAINT "fk_quota_user"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."production_logs" DROP CONSTRAINT "fk_plog_creator"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."production_logs" DROP CONSTRAINT "fk_plog_season"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."production_log_notes" DROP CONSTRAINT "fk_plog_note_creator"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."production_log_notes" DROP CONSTRAINT "fk_plog_note_log"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."product_reviews" DROP CONSTRAINT "fk_review_reviewer"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."product_reviews" DROP CONSTRAINT "fk_review_token"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."product_certifications" DROP CONSTRAINT "fk_pc_cert"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."product_certifications" DROP CONSTRAINT "fk_pc_product"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."orders" DROP CONSTRAINT "fk_order_buyer"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."orders" DROP CONSTRAINT "fk_order_org"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."orders" DROP CONSTRAINT "fk_order_product"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."orders" DROP CONSTRAINT "fk_order_quotation"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."orders" DROP CONSTRAINT "fk_order_seller"`);
        await queryRunner.query(`DROP INDEX "media"."idx_media_created_brin"`);
        await queryRunner.query(`DROP INDEX "identity"."idx_profiles_location"`);
        await queryRunner.query(`DROP INDEX "identity"."idx_profiles_verified"`);
        await queryRunner.query(`DROP INDEX "identity"."idx_users_plan"`);
        await queryRunner.query(`DROP INDEX "identity"."idx_users_plan_expires"`);
        await queryRunner.query(`DROP INDEX "identity"."uq_users_email_active"`);
        await queryRunner.query(`DROP INDEX "identity"."uq_users_phone_active"`);
        await queryRunner.query(`DROP INDEX "identity"."idx_users_email"`);
        await queryRunner.query(`DROP INDEX "identity"."idx_users_phone"`);
        await queryRunner.query(`DROP INDEX "system"."idx_mw_active"`);
        await queryRunner.query(`DROP INDEX "system"."idx_feature_flags_key"`);
        await queryRunner.query(`DROP INDEX "identity"."idx_org_slug"`);
        await queryRunner.query(`DROP INDEX "identity"."idx_org_province"`);
        await queryRunner.query(`DROP INDEX "identity"."idx_org_location"`);
        await queryRunner.query(`DROP INDEX "social_graph"."uq_follow_user"`);
        await queryRunner.query(`DROP INDEX "social_graph"."uq_follow_org"`);
        await queryRunner.query(`DROP INDEX "notification"."idx_notif_entity"`);
        await queryRunner.query(`DROP INDEX "notification"."idx_notif_brin"`);
        await queryRunner.query(`DROP INDEX "moderation"."idx_mmf_media_id"`);
        await queryRunner.query(`DROP INDEX "moderation"."idx_mmf_status"`);
        await queryRunner.query(`DROP INDEX "moderation"."idx_mmf_verdict"`);
        await queryRunner.query(`DROP INDEX "moderation"."idx_reports_status"`);
        await queryRunner.query(`DROP INDEX "moderation"."idx_reports_reporter"`);
        await queryRunner.query(`DROP INDEX "moderation"."idx_media_hashes_owner"`);
        await queryRunner.query(`DROP INDEX "moderation"."idx_media_hashes_purpose"`);
        await queryRunner.query(`DROP INDEX "moderation"."idx_audit_user"`);
        await queryRunner.query(`DROP INDEX "moderation"."idx_audit_resource"`);
        await queryRunner.query(`DROP INDEX "moderation"."idx_audit_brin"`);
        await queryRunner.query(`DROP INDEX "messaging"."idx_conv_last_msg"`);
        await queryRunner.query(`DROP INDEX "messaging"."idx_msg_conv"`);
        await queryRunner.query(`DROP INDEX "messaging"."idx_msg_sender"`);
        await queryRunner.query(`DROP INDEX "messaging"."idx_msg_brin"`);
        await queryRunner.query(`DROP INDEX "identity"."idx_verif_pending"`);
        await queryRunner.query(`DROP INDEX "identity"."idx_sessions_token"`);
        await queryRunner.query(`DROP INDEX "identity"."idx_sessions_expires"`);
        await queryRunner.query(`DROP INDEX "identity"."idx_org_member_active"`);
        await queryRunner.query(`DROP INDEX "content"."idx_post_tags_ref"`);
        await queryRunner.query(`DROP INDEX "content"."idx_posts_author"`);
        await queryRunner.query(`DROP INDEX "content"."idx_posts_visibility"`);
        await queryRunner.query(`DROP INDEX "content"."idx_posts_source"`);
        await queryRunner.query(`DROP INDEX "content"."idx_posts_external_url"`);
        await queryRunner.query(`DROP INDEX "content"."idx_posts_brin"`);
        await queryRunner.query(`DROP INDEX "engagement"."uq_shares_repost"`);
        await queryRunner.query(`DROP INDEX "engagement"."idx_shares_user"`);
        await queryRunner.query(`DROP INDEX "engagement"."idx_comments_post"`);
        await queryRunner.query(`DROP INDEX "engagement"."idx_comments_parent"`);
        await queryRunner.query(`DROP INDEX "engagement"."idx_comments_author"`);
        await queryRunner.query(`DROP INDEX "analytics"."idx_ual_user"`);
        await queryRunner.query(`DROP INDEX "analytics"."idx_ual_action"`);
        await queryRunner.query(`DROP INDEX "analytics"."idx_ual_entity"`);
        await queryRunner.query(`DROP INDEX "analytics"."idx_ual_brin"`);
        await queryRunner.query(`DROP INDEX "agriculture"."idx_cert_expiry"`);
        await queryRunner.query(`DROP INDEX "agriculture"."idx_gp_location"`);
        await queryRunner.query(`ALTER TABLE "media"."media" DROP CONSTRAINT "media_media_type_check"`);
        await queryRunner.query(`ALTER TABLE "media"."media" DROP CONSTRAINT "media_file_size_bytes_check"`);
        await queryRunner.query(`ALTER TABLE "media"."media" DROP CONSTRAINT "media_processing_status_check"`);
        await queryRunner.query(`ALTER TABLE "identity"."profiles" DROP CONSTRAINT "profiles_bio_check"`);
        await queryRunner.query(`ALTER TABLE "identity"."profiles" DROP CONSTRAINT "profiles_follower_count_check"`);
        await queryRunner.query(`ALTER TABLE "identity"."profiles" DROP CONSTRAINT "profiles_following_count_check"`);
        await queryRunner.query(`ALTER TABLE "identity"."profiles" DROP CONSTRAINT "profiles_post_count_check"`);
        await queryRunner.query(`ALTER TABLE "identity"."users" DROP CONSTRAINT "chk_users_contact"`);
        await queryRunner.query(`ALTER TABLE "identity"."users" DROP CONSTRAINT "users_signup_channel_check"`);
        await queryRunner.query(`ALTER TABLE "system"."maintenance_windows" DROP CONSTRAINT "maintenance_windows_scope_check"`);
        await queryRunner.query(`ALTER TABLE "system"."feature_flags" DROP CONSTRAINT "feature_flags_rollout_percentage_check"`);
        await queryRunner.query(`ALTER TABLE "system"."app_versions" DROP CONSTRAINT "app_versions_platform_check"`);
        await queryRunner.query(`ALTER TABLE "identity"."organizations" DROP CONSTRAINT "organizations_follower_count_check"`);
        await queryRunner.query(`ALTER TABLE "identity"."organizations" DROP CONSTRAINT "chk_org_slug"`);
        await queryRunner.query(`ALTER TABLE "social_graph"."follows" DROP CONSTRAINT "follows_status_check"`);
        await queryRunner.query(`ALTER TABLE "social_graph"."follows" DROP CONSTRAINT "chk_follow_target"`);
        await queryRunner.query(`ALTER TABLE "moderation"."reports" DROP CONSTRAINT "reports_target_type_check"`);
        await queryRunner.query(`ALTER TABLE "messaging"."conversations" DROP CONSTRAINT "conversations_conversation_type_check"`);
        await queryRunner.query(`ALTER TABLE "messaging"."messages" DROP CONSTRAINT "messages_message_type_check"`);
        await queryRunner.query(`ALTER TABLE "messaging"."messages" DROP CONSTRAINT "chk_msg_body"`);
        await queryRunner.query(`ALTER TABLE "identity"."verification_requests" DROP CONSTRAINT "verification_requests_document_type_check"`);
        await queryRunner.query(`ALTER TABLE "identity"."verification_requests" DROP CONSTRAINT "verification_requests_status_check"`);
        await queryRunner.query(`ALTER TABLE "identity"."user_settings" DROP CONSTRAINT "user_settings_language_check"`);
        await queryRunner.query(`ALTER TABLE "identity"."user_settings" DROP CONSTRAINT "user_settings_theme_check"`);
        await queryRunner.query(`ALTER TABLE "identity"."user_settings" DROP CONSTRAINT "user_settings_who_can_follow_check"`);
        await queryRunner.query(`ALTER TABLE "identity"."user_settings" DROP CONSTRAINT "user_settings_who_can_message_check"`);
        await queryRunner.query(`ALTER TABLE "identity"."user_sessions" DROP CONSTRAINT "user_sessions_platform_check"`);
        await queryRunner.query(`ALTER TABLE "identity"."organization_members" DROP CONSTRAINT "organization_members_org_role_check"`);
        await queryRunner.query(`ALTER TABLE "identity"."organization_members" DROP CONSTRAINT "organization_members_status_check"`);
        await queryRunner.query(`ALTER TABLE "identity"."fcm_devices" DROP CONSTRAINT "fcm_devices_platform_check"`);
        await queryRunner.query(`ALTER TABLE "content"."post_tags" DROP CONSTRAINT "post_tags_tag_type_check"`);
        await queryRunner.query(`ALTER TABLE "content"."posts" DROP CONSTRAINT "posts_body_check"`);
        await queryRunner.query(`ALTER TABLE "content"."posts" DROP CONSTRAINT "posts_external_click_count_check"`);
        await queryRunner.query(`ALTER TABLE "content"."posts" DROP CONSTRAINT "posts_reaction_count_check"`);
        await queryRunner.query(`ALTER TABLE "content"."posts" DROP CONSTRAINT "posts_comment_count_check"`);
        await queryRunner.query(`ALTER TABLE "content"."posts" DROP CONSTRAINT "posts_share_count_check"`);
        await queryRunner.query(`ALTER TABLE "content"."posts" DROP CONSTRAINT "posts_view_count_check"`);
        await queryRunner.query(`ALTER TABLE "content"."posts" DROP CONSTRAINT "posts_source_check"`);
        await queryRunner.query(`ALTER TABLE "engagement"."shares" DROP CONSTRAINT "shares_share_type_check"`);
        await queryRunner.query(`ALTER TABLE "engagement"."reactions" DROP CONSTRAINT "reactions_target_type_check"`);
        await queryRunner.query(`ALTER TABLE "engagement"."comments" DROP CONSTRAINT "comments_like_count_check"`);
        await queryRunner.query(`ALTER TABLE "engagement"."comments" DROP CONSTRAINT "comments_body_check"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."green_profiles" DROP CONSTRAINT "chk_gp_owner"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."public_trace_tokens" DROP CONSTRAINT "public_trace_tokens_target_type_check"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_quota_tracking" DROP CONSTRAINT "chk_quota_owner"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."product_reviews" DROP CONSTRAINT "product_reviews_rating_check"`);
        await queryRunner.query(`ALTER TABLE "system"."app_versions" DROP CONSTRAINT "app_versions_platform_latest_version_key"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."batches" DROP CONSTRAINT "batches_product_id_batch_code_key"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_quota_tracking" DROP CONSTRAINT "qr_quota_tracking_user_id_billing_period_key"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_quota_tracking" DROP CONSTRAINT "qr_quota_tracking_organization_id_billing_period_key"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."product_reviews" DROP CONSTRAINT "product_reviews_token_id_reviewer_id_key"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."certifications" ADD "admin_note" text`);
        await queryRunner.query(`ALTER TABLE "agriculture"."certifications" ADD "reviewed_by" uuid`);
        await queryRunner.query(`ALTER TABLE "agriculture"."certifications" ADD "reviewed_at" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "moderation"."audit_logs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "moderation"."audit_logs" ALTER COLUMN "id" SET DEFAULT uuid_generate_v7()`);
        await queryRunner.query(`ALTER TABLE "moderation"."audit_logs" DROP COLUMN "actor_role"`);
        await queryRunner.query(`CREATE TYPE "moderation"."user_role" AS ENUM('consumer', 'seller', 'cooperative', 'enterprise', 'expert', 'admin')`);
        await queryRunner.query(`ALTER TABLE "moderation"."audit_logs" ADD "actor_role" "moderation"."user_role"`);
        await queryRunner.query(`ALTER TABLE "analytics"."user_activity_logs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "analytics"."user_activity_logs" ALTER COLUMN "id" SET DEFAULT uuid_generate_v7()`);
        await queryRunner.query(`DROP VIEW IF EXISTS agriculture.v_green_profile_cert_summary`);
        await queryRunner.query(`ALTER TYPE "agriculture"."certification_status" RENAME TO "certification_status_old"`);
        await queryRunner.query(`CREATE TYPE "agriculture"."certification_status" AS ENUM('pending', 'approved', 'rejected', 'valid', 'expired', 'pending_renewal', 'revoked')`);
        await queryRunner.query(`ALTER TABLE "agriculture"."certifications" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "agriculture"."certifications" ALTER COLUMN "status" TYPE "agriculture"."certification_status" USING "status"::"text"::"agriculture"."certification_status"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."certifications" ALTER COLUMN "status" SET DEFAULT 'valid'`);
        await queryRunner.query(`DROP TYPE "agriculture"."certification_status_old"`);
        await queryRunner.query(`
            CREATE OR REPLACE VIEW agriculture.v_green_profile_cert_summary AS
            SELECT
                gp.id                                          AS green_profile_id,
                gp.profile_name,
                COUNT(c.id) FILTER (WHERE c.status = 'valid') AS valid_cert_count,
                MAX(c.expiry_date)                             AS latest_expiry
            FROM agriculture.green_profiles gp
            LEFT JOIN agriculture.certifications c ON c.green_profile_id = gp.id
            WHERE gp.deleted_at IS NULL
            GROUP BY gp.id, gp.profile_name
        `);
        await queryRunner.query(`ALTER TABLE "agriculture"."public_trace_tokens" ALTER COLUMN "token" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "agriculture"."public_trace_tokens" ALTER COLUMN "token" SET DEFAULT uuid_generate_v7()`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_scans" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_scans" ALTER COLUMN "id" SET DEFAULT uuid_generate_v7()`);
        await queryRunner.query(`CREATE INDEX "idx_msg_conv" ON "messaging"."messages" ("conversation_id") `);
        await queryRunner.query(`CREATE INDEX "idx_posts_visibility" ON "content"."posts" ("visibility") `);
        await queryRunner.query(`CREATE INDEX "idx_posts_author" ON "content"."posts" ("author_id") `);
        await queryRunner.query(`CREATE INDEX "idx_comments_post" ON "engagement"."comments" ("post_id") `);
        await queryRunner.query(`ALTER TABLE "system"."app_versions" ADD CONSTRAINT "UQ_2f97b90f08787cca9d5a569ca57" UNIQUE ("platform", "latest_version")`);
        await queryRunner.query(`ALTER TABLE "social_graph"."follows" ADD CONSTRAINT "uq_follow" UNIQUE ("follower_id", "followee_user_id", "followee_org_id")`);
        await queryRunner.query(`ALTER TABLE "agriculture"."batches" ADD CONSTRAINT "uq_batch_code" UNIQUE ("product_id", "batch_code")`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_quota_tracking" ADD CONSTRAINT "uq_quota_org" UNIQUE ("organization_id", "billing_period")`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_quota_tracking" ADD CONSTRAINT "uq_quota_user" UNIQUE ("user_id", "billing_period")`);
        await queryRunner.query(`ALTER TABLE "agriculture"."product_reviews" ADD CONSTRAINT "uq_product_review" UNIQUE ("token_id", "reviewer_id")`);
        await queryRunner.query(`ALTER TABLE "media"."media" ADD CONSTRAINT "FK_8bd1ad5f79df58cfd7ad9c42fb5" FOREIGN KEY ("uploader_id") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."profiles" ADD CONSTRAINT "FK_9e432b7df0d182f8d292902d1a2" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."profiles" ADD CONSTRAINT "FK_b30f5284886a896989b8ff94223" FOREIGN KEY ("avatar_media_id") REFERENCES "media"."media"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."profiles" ADD CONSTRAINT "FK_9a88ee86fd9bd9aa07d39b83e00" FOREIGN KEY ("cover_media_id") REFERENCES "media"."media"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system"."maintenance_windows" ADD CONSTRAINT "FK_d6e1a7bef873563a9638a1d3a3b" FOREIGN KEY ("created_by") REFERENCES "identity"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system"."maintenance_windows" ADD CONSTRAINT "FK_c35e49d7a5a8f2b4c8846340e1d" FOREIGN KEY ("updated_by") REFERENCES "identity"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system"."app_versions" ADD CONSTRAINT "FK_858c56ae4b32fec3bf3eeb85a86" FOREIGN KEY ("created_by") REFERENCES "identity"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "social_graph"."blocks" ADD CONSTRAINT "FK_74f530c6fbffc357047b263818d" FOREIGN KEY ("blocker_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "social_graph"."blocks" ADD CONSTRAINT "FK_8aa6c887bed61ad10829450f2f0" FOREIGN KEY ("blocked_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."organizations" ADD CONSTRAINT "FK_a8afaf18799fd187cbe8e998dcd" FOREIGN KEY ("owner_user_id") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."organizations" ADD CONSTRAINT "FK_732baf9cb000a1cf963c253319e" FOREIGN KEY ("logo_media_id") REFERENCES "media"."media"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."organizations" ADD CONSTRAINT "FK_f5ffed24f37f09bae9df8c49f35" FOREIGN KEY ("cover_media_id") REFERENCES "media"."media"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "social_graph"."follows" ADD CONSTRAINT "FK_54b5dc2739f2dea57900933db66" FOREIGN KEY ("follower_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "social_graph"."follows" ADD CONSTRAINT "FK_fd9a87e1cf7c5a1ba176fcfb7ae" FOREIGN KEY ("followee_user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "social_graph"."follows" ADD CONSTRAINT "FK_1e17e6f94a59762a6166a8646a0" FOREIGN KEY ("followee_org_id") REFERENCES "identity"."organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification"."notifications" ADD CONSTRAINT "FK_5332a4daa46fd3f4e6625dd275d" FOREIGN KEY ("recipient_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification"."notifications" ADD CONSTRAINT "FK_20f8b51fd9655c0b69feed5efc6" FOREIGN KEY ("actor_id") REFERENCES "identity"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "moderation"."reports" ADD CONSTRAINT "FK_9459b9bf907a3807ef7143d2ead" FOREIGN KEY ("reporter_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "moderation"."reports" ADD CONSTRAINT "FK_69dacf83efaa6e97bcaa6c648e8" FOREIGN KEY ("actioned_by") REFERENCES "identity"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messaging"."messages" ADD CONSTRAINT "FK_3bc55a7c3f9ed54b520bb5cfe23" FOREIGN KEY ("conversation_id") REFERENCES "messaging"."conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messaging"."messages" ADD CONSTRAINT "FK_22133395bd13b970ccd0c34ab22" FOREIGN KEY ("sender_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messaging"."messages" ADD CONSTRAINT "FK_a3ad437aa7b8f8a5a9093819aea" FOREIGN KEY ("media_id") REFERENCES "media"."media"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messaging"."conversation_members" ADD CONSTRAINT "FK_36340a1704b039608e34244511f" FOREIGN KEY ("conversation_id") REFERENCES "messaging"."conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messaging"."conversation_members" ADD CONSTRAINT "FK_a46c76be8f62c4b00a835cdc370" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."verification_requests" ADD CONSTRAINT "FK_44f76cc6635620daadc8229d7db" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."verification_requests" ADD CONSTRAINT "FK_1dfa9b51f7bdc2d989406b91350" FOREIGN KEY ("organization_id") REFERENCES "identity"."organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."verification_requests" ADD CONSTRAINT "FK_461cc3f0c58eadf9a18b6a36af9" FOREIGN KEY ("reviewed_by") REFERENCES "identity"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."user_settings" ADD CONSTRAINT "FK_4ed056b9344e6f7d8d46ec4b302" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."user_sessions" ADD CONSTRAINT "FK_e9658e959c490b0a634dfc54783" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."rbac_role_permissions" ADD CONSTRAINT "FK_6eb94e2e9d283993bc7c2f01603" FOREIGN KEY ("role_id") REFERENCES "identity"."rbac_roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."rbac_role_permissions" ADD CONSTRAINT "FK_6e03d8aa0ac0be56a799875ac4d" FOREIGN KEY ("permission_id") REFERENCES "identity"."rbac_permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."organization_members" ADD CONSTRAINT "FK_7062a4fbd9bab22ffd918e5d3d9" FOREIGN KEY ("organization_id") REFERENCES "identity"."organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."organization_members" ADD CONSTRAINT "FK_89bde91f78d36ca41e9515d91c6" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."organization_members" ADD CONSTRAINT "FK_78252b40612aaddc2138eadc810" FOREIGN KEY ("invited_by") REFERENCES "identity"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."fcm_devices" ADD CONSTRAINT "FK_cee8e59b0b919e0f0fea8a8e894" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content"."post_media" ADD CONSTRAINT "FK_1eeb54a4fdfbe9db17899243cbe" FOREIGN KEY ("post_id") REFERENCES "content"."posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content"."post_media" ADD CONSTRAINT "FK_a759d9accb8e41ae25c357e5ed3" FOREIGN KEY ("media_id") REFERENCES "media"."media"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content"."post_hashtags" ADD CONSTRAINT "FK_6c16a0f366b0642259bbe50481c" FOREIGN KEY ("post_id") REFERENCES "content"."posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content"."post_hashtags" ADD CONSTRAINT "FK_41f5ee7a97e67023d7461fa8f43" FOREIGN KEY ("hashtag_id") REFERENCES "content"."hashtags"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content"."post_tags" ADD CONSTRAINT "FK_5df4e8dc2cb3e668b962362265d" FOREIGN KEY ("post_id") REFERENCES "content"."posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content"."posts" ADD CONSTRAINT "FK_312c63be865c81b922e39c2475e" FOREIGN KEY ("author_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content"."posts" ADD CONSTRAINT "FK_4ab12e7158409f03cd24db7b7c9" FOREIGN KEY ("org_id") REFERENCES "identity"."organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "engagement"."shares" ADD CONSTRAINT "FK_a8aded2f90f448876f7fe63eab4" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "engagement"."shares" ADD CONSTRAINT "FK_876fddcf3965fbcd1dd78a4b283" FOREIGN KEY ("post_id") REFERENCES "content"."posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "engagement"."reactions" ADD CONSTRAINT "FK_dde6062145a93649adc5af3946e" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "engagement"."comments" ADD CONSTRAINT "FK_259bf9825d9d198608d1b46b0b5" FOREIGN KEY ("post_id") REFERENCES "content"."posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "engagement"."comments" ADD CONSTRAINT "FK_e6d38899c31997c45d128a8973b" FOREIGN KEY ("author_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "engagement"."comments" ADD CONSTRAINT "FK_93ce08bdbea73c0c7ee673ec35a" FOREIGN KEY ("parent_comment_id") REFERENCES "engagement"."comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "engagement"."comments" ADD CONSTRAINT "FK_b7c58a347104bdc579d508fb52f" FOREIGN KEY ("reply_to_user_id") REFERENCES "identity"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."certifications" ADD CONSTRAINT "FK_f24e386d9c7081f3717ee86bdd8" FOREIGN KEY ("green_profile_id") REFERENCES "agriculture"."green_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."green_profiles" ADD CONSTRAINT "FK_0f771141c0382414914f451cf20" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."green_profiles" ADD CONSTRAINT "FK_88c955ad6df68fc6a903b5a51ea" FOREIGN KEY ("organization_id") REFERENCES "identity"."organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."categories" ADD CONSTRAINT "FK_88cea2dc9c31951d06437879b40" FOREIGN KEY ("parent_id") REFERENCES "agriculture"."categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."products" ADD CONSTRAINT "FK_4e70935f63e95bf2c0d16399289" FOREIGN KEY ("owner_user_id") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."products" ADD CONSTRAINT "FK_2d404aa7aa4a0404eafd1840915" FOREIGN KEY ("organization_id") REFERENCES "identity"."organizations"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."products" ADD CONSTRAINT "FK_859ac9b5035061c6b6c21cbc21c" FOREIGN KEY ("green_profile_id") REFERENCES "agriculture"."green_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."products" ADD CONSTRAINT "FK_9a5f6868c96e0069e699f33e124" FOREIGN KEY ("category_id") REFERENCES "agriculture"."categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."trade_posts" ADD CONSTRAINT "FK_4e182b32d7062cb553c0d9a51df" FOREIGN KEY ("poster_user_id") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."trade_posts" ADD CONSTRAINT "FK_0b4eea19107b82f1b101a401a05" FOREIGN KEY ("organization_id") REFERENCES "identity"."organizations"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."trade_posts" ADD CONSTRAINT "FK_be29f03234bf66b98d94e08d212" FOREIGN KEY ("product_id") REFERENCES "agriculture"."products"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."trade_posts" ADD CONSTRAINT "FK_dcfb054aa74dc8456d0d89e8b8d" FOREIGN KEY ("category_id") REFERENCES "agriculture"."categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."quotations" ADD CONSTRAINT "FK_77b45a9f2d8a21f09041000fb94" FOREIGN KEY ("trade_post_id") REFERENCES "agriculture"."trade_posts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."quotations" ADD CONSTRAINT "FK_c7fda797648d1f6c7750e6ddb3c" FOREIGN KEY ("sender_user_id") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."quotations" ADD CONSTRAINT "FK_d3a4452d731d438dd24c8280313" FOREIGN KEY ("receiver_user_id") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."quotations" ADD CONSTRAINT "FK_e173cf45299e8591b80924e2a13" FOREIGN KEY ("product_id") REFERENCES "agriculture"."products"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."crop_seasons" ADD CONSTRAINT "FK_16ec3e84dabdeb578dab215110c" FOREIGN KEY ("green_profile_id") REFERENCES "agriculture"."green_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."crop_seasons" ADD CONSTRAINT "FK_a2b23b53ef1fc727b430780e6cf" FOREIGN KEY ("product_id") REFERENCES "agriculture"."products"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."crop_seasons" ADD CONSTRAINT "FK_df6b8c97bc388ddd6bd39671af2" FOREIGN KEY ("organization_id") REFERENCES "identity"."organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."crop_seasons" ADD CONSTRAINT "FK_fd1ffc75248d215366f2e6b2607" FOREIGN KEY ("created_by") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."batches" ADD CONSTRAINT "FK_07ad38527d0d87601f3b05a6a22" FOREIGN KEY ("product_id") REFERENCES "agriculture"."products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."batches" ADD CONSTRAINT "FK_78ce809386d71b7b60c462a19d1" FOREIGN KEY ("crop_season_id") REFERENCES "agriculture"."crop_seasons"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."batches" ADD CONSTRAINT "FK_4b2517a8fe382ec5287d3ee6021" FOREIGN KEY ("green_profile_id") REFERENCES "agriculture"."green_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."batches" ADD CONSTRAINT "FK_f170c66d44ca6ea3aa741ef5f4c" FOREIGN KEY ("created_by") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."public_trace_tokens" ADD CONSTRAINT "FK_c5d1b203e5d4e62293ef6227cce" FOREIGN KEY ("product_id") REFERENCES "agriculture"."products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."public_trace_tokens" ADD CONSTRAINT "FK_d51d97efacebcf60eb8dd4d6253" FOREIGN KEY ("batch_id") REFERENCES "agriculture"."batches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."public_trace_tokens" ADD CONSTRAINT "FK_f3b0b8966d18151f5fd424cd9a4" FOREIGN KEY ("created_by") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_scans" ADD CONSTRAINT "FK_d6bc6faa6e51d96268de3fe0427" FOREIGN KEY ("token_id") REFERENCES "agriculture"."public_trace_tokens"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_quota_tracking" ADD CONSTRAINT "FK_73c278f338f5452a15a5152a43a" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_quota_tracking" ADD CONSTRAINT "FK_b56d7a40803d40352f3e415520a" FOREIGN KEY ("organization_id") REFERENCES "identity"."organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."production_logs" ADD CONSTRAINT "FK_2cb6efea4a47b26197ff7a5204a" FOREIGN KEY ("crop_season_id") REFERENCES "agriculture"."crop_seasons"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."production_logs" ADD CONSTRAINT "FK_113d4e31bded04973bb7bfdf217" FOREIGN KEY ("created_by") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."production_log_notes" ADD CONSTRAINT "FK_00d9ecf39c6858f1194ecbfc323" FOREIGN KEY ("log_id") REFERENCES "agriculture"."production_logs"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."production_log_notes" ADD CONSTRAINT "FK_5c057ade37dcef1a26de7da464b" FOREIGN KEY ("created_by") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."product_reviews" ADD CONSTRAINT "FK_c976c9ba3f623edbab7f4cfc1a4" FOREIGN KEY ("token_id") REFERENCES "agriculture"."public_trace_tokens"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."product_reviews" ADD CONSTRAINT "FK_a2ffe4b13d499c0e8aa165996c6" FOREIGN KEY ("reviewer_id") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."product_certifications" ADD CONSTRAINT "FK_4ac2b9fb94b2cbe43d0fe493c80" FOREIGN KEY ("product_id") REFERENCES "agriculture"."products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."product_certifications" ADD CONSTRAINT "FK_a42f201d71c685db11bbd192926" FOREIGN KEY ("certification_id") REFERENCES "agriculture"."certifications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."orders" ADD CONSTRAINT "FK_52eb1e54753dda6b4b504c04fb1" FOREIGN KEY ("quotation_id") REFERENCES "agriculture"."quotations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."orders" ADD CONSTRAINT "FK_5e90e93d0e036c3fadbaefa4d0a" FOREIGN KEY ("buyer_id") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."orders" ADD CONSTRAINT "FK_ef6710c78c6fbc26d1ba58268ab" FOREIGN KEY ("seller_id") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."orders" ADD CONSTRAINT "FK_3b13df1eb3b062fd5ed4ebc53bf" FOREIGN KEY ("organization_id") REFERENCES "identity"."organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."orders" ADD CONSTRAINT "FK_ac832121b6c331b084ecc4121fd" FOREIGN KEY ("product_id") REFERENCES "agriculture"."products"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "agriculture"."orders" DROP CONSTRAINT "FK_ac832121b6c331b084ecc4121fd"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."orders" DROP CONSTRAINT "FK_3b13df1eb3b062fd5ed4ebc53bf"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."orders" DROP CONSTRAINT "FK_ef6710c78c6fbc26d1ba58268ab"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."orders" DROP CONSTRAINT "FK_5e90e93d0e036c3fadbaefa4d0a"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."orders" DROP CONSTRAINT "FK_52eb1e54753dda6b4b504c04fb1"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."product_certifications" DROP CONSTRAINT "FK_a42f201d71c685db11bbd192926"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."product_certifications" DROP CONSTRAINT "FK_4ac2b9fb94b2cbe43d0fe493c80"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."product_reviews" DROP CONSTRAINT "FK_a2ffe4b13d499c0e8aa165996c6"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."product_reviews" DROP CONSTRAINT "FK_c976c9ba3f623edbab7f4cfc1a4"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."production_log_notes" DROP CONSTRAINT "FK_5c057ade37dcef1a26de7da464b"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."production_log_notes" DROP CONSTRAINT "FK_00d9ecf39c6858f1194ecbfc323"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."production_logs" DROP CONSTRAINT "FK_113d4e31bded04973bb7bfdf217"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."production_logs" DROP CONSTRAINT "FK_2cb6efea4a47b26197ff7a5204a"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_quota_tracking" DROP CONSTRAINT "FK_b56d7a40803d40352f3e415520a"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_quota_tracking" DROP CONSTRAINT "FK_73c278f338f5452a15a5152a43a"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_scans" DROP CONSTRAINT "FK_d6bc6faa6e51d96268de3fe0427"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."public_trace_tokens" DROP CONSTRAINT "FK_f3b0b8966d18151f5fd424cd9a4"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."public_trace_tokens" DROP CONSTRAINT "FK_d51d97efacebcf60eb8dd4d6253"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."public_trace_tokens" DROP CONSTRAINT "FK_c5d1b203e5d4e62293ef6227cce"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."batches" DROP CONSTRAINT "FK_f170c66d44ca6ea3aa741ef5f4c"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."batches" DROP CONSTRAINT "FK_4b2517a8fe382ec5287d3ee6021"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."batches" DROP CONSTRAINT "FK_78ce809386d71b7b60c462a19d1"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."batches" DROP CONSTRAINT "FK_07ad38527d0d87601f3b05a6a22"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."crop_seasons" DROP CONSTRAINT "FK_fd1ffc75248d215366f2e6b2607"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."crop_seasons" DROP CONSTRAINT "FK_df6b8c97bc388ddd6bd39671af2"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."crop_seasons" DROP CONSTRAINT "FK_a2b23b53ef1fc727b430780e6cf"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."crop_seasons" DROP CONSTRAINT "FK_16ec3e84dabdeb578dab215110c"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."quotations" DROP CONSTRAINT "FK_e173cf45299e8591b80924e2a13"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."quotations" DROP CONSTRAINT "FK_d3a4452d731d438dd24c8280313"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."quotations" DROP CONSTRAINT "FK_c7fda797648d1f6c7750e6ddb3c"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."quotations" DROP CONSTRAINT "FK_77b45a9f2d8a21f09041000fb94"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."trade_posts" DROP CONSTRAINT "FK_dcfb054aa74dc8456d0d89e8b8d"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."trade_posts" DROP CONSTRAINT "FK_be29f03234bf66b98d94e08d212"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."trade_posts" DROP CONSTRAINT "FK_0b4eea19107b82f1b101a401a05"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."trade_posts" DROP CONSTRAINT "FK_4e182b32d7062cb553c0d9a51df"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."products" DROP CONSTRAINT "FK_9a5f6868c96e0069e699f33e124"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."products" DROP CONSTRAINT "FK_859ac9b5035061c6b6c21cbc21c"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."products" DROP CONSTRAINT "FK_2d404aa7aa4a0404eafd1840915"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."products" DROP CONSTRAINT "FK_4e70935f63e95bf2c0d16399289"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."categories" DROP CONSTRAINT "FK_88cea2dc9c31951d06437879b40"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."green_profiles" DROP CONSTRAINT "FK_88c955ad6df68fc6a903b5a51ea"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."green_profiles" DROP CONSTRAINT "FK_0f771141c0382414914f451cf20"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."certifications" DROP CONSTRAINT "FK_f24e386d9c7081f3717ee86bdd8"`);
        await queryRunner.query(`ALTER TABLE "engagement"."comments" DROP CONSTRAINT "FK_b7c58a347104bdc579d508fb52f"`);
        await queryRunner.query(`ALTER TABLE "engagement"."comments" DROP CONSTRAINT "FK_93ce08bdbea73c0c7ee673ec35a"`);
        await queryRunner.query(`ALTER TABLE "engagement"."comments" DROP CONSTRAINT "FK_e6d38899c31997c45d128a8973b"`);
        await queryRunner.query(`ALTER TABLE "engagement"."comments" DROP CONSTRAINT "FK_259bf9825d9d198608d1b46b0b5"`);
        await queryRunner.query(`ALTER TABLE "engagement"."reactions" DROP CONSTRAINT "FK_dde6062145a93649adc5af3946e"`);
        await queryRunner.query(`ALTER TABLE "engagement"."shares" DROP CONSTRAINT "FK_876fddcf3965fbcd1dd78a4b283"`);
        await queryRunner.query(`ALTER TABLE "engagement"."shares" DROP CONSTRAINT "FK_a8aded2f90f448876f7fe63eab4"`);
        await queryRunner.query(`ALTER TABLE "content"."posts" DROP CONSTRAINT "FK_4ab12e7158409f03cd24db7b7c9"`);
        await queryRunner.query(`ALTER TABLE "content"."posts" DROP CONSTRAINT "FK_312c63be865c81b922e39c2475e"`);
        await queryRunner.query(`ALTER TABLE "content"."post_tags" DROP CONSTRAINT "FK_5df4e8dc2cb3e668b962362265d"`);
        await queryRunner.query(`ALTER TABLE "content"."post_hashtags" DROP CONSTRAINT "FK_41f5ee7a97e67023d7461fa8f43"`);
        await queryRunner.query(`ALTER TABLE "content"."post_hashtags" DROP CONSTRAINT "FK_6c16a0f366b0642259bbe50481c"`);
        await queryRunner.query(`ALTER TABLE "content"."post_media" DROP CONSTRAINT "FK_a759d9accb8e41ae25c357e5ed3"`);
        await queryRunner.query(`ALTER TABLE "content"."post_media" DROP CONSTRAINT "FK_1eeb54a4fdfbe9db17899243cbe"`);
        await queryRunner.query(`ALTER TABLE "identity"."fcm_devices" DROP CONSTRAINT "FK_cee8e59b0b919e0f0fea8a8e894"`);
        await queryRunner.query(`ALTER TABLE "identity"."organization_members" DROP CONSTRAINT "FK_78252b40612aaddc2138eadc810"`);
        await queryRunner.query(`ALTER TABLE "identity"."organization_members" DROP CONSTRAINT "FK_89bde91f78d36ca41e9515d91c6"`);
        await queryRunner.query(`ALTER TABLE "identity"."organization_members" DROP CONSTRAINT "FK_7062a4fbd9bab22ffd918e5d3d9"`);
        await queryRunner.query(`ALTER TABLE "identity"."rbac_role_permissions" DROP CONSTRAINT "FK_6e03d8aa0ac0be56a799875ac4d"`);
        await queryRunner.query(`ALTER TABLE "identity"."rbac_role_permissions" DROP CONSTRAINT "FK_6eb94e2e9d283993bc7c2f01603"`);
        await queryRunner.query(`ALTER TABLE "identity"."user_sessions" DROP CONSTRAINT "FK_e9658e959c490b0a634dfc54783"`);
        await queryRunner.query(`ALTER TABLE "identity"."user_settings" DROP CONSTRAINT "FK_4ed056b9344e6f7d8d46ec4b302"`);
        await queryRunner.query(`ALTER TABLE "identity"."verification_requests" DROP CONSTRAINT "FK_461cc3f0c58eadf9a18b6a36af9"`);
        await queryRunner.query(`ALTER TABLE "identity"."verification_requests" DROP CONSTRAINT "FK_1dfa9b51f7bdc2d989406b91350"`);
        await queryRunner.query(`ALTER TABLE "identity"."verification_requests" DROP CONSTRAINT "FK_44f76cc6635620daadc8229d7db"`);
        await queryRunner.query(`ALTER TABLE "messaging"."conversation_members" DROP CONSTRAINT "FK_a46c76be8f62c4b00a835cdc370"`);
        await queryRunner.query(`ALTER TABLE "messaging"."conversation_members" DROP CONSTRAINT "FK_36340a1704b039608e34244511f"`);
        await queryRunner.query(`ALTER TABLE "messaging"."messages" DROP CONSTRAINT "FK_a3ad437aa7b8f8a5a9093819aea"`);
        await queryRunner.query(`ALTER TABLE "messaging"."messages" DROP CONSTRAINT "FK_22133395bd13b970ccd0c34ab22"`);
        await queryRunner.query(`ALTER TABLE "messaging"."messages" DROP CONSTRAINT "FK_3bc55a7c3f9ed54b520bb5cfe23"`);
        await queryRunner.query(`ALTER TABLE "moderation"."reports" DROP CONSTRAINT "FK_69dacf83efaa6e97bcaa6c648e8"`);
        await queryRunner.query(`ALTER TABLE "moderation"."reports" DROP CONSTRAINT "FK_9459b9bf907a3807ef7143d2ead"`);
        await queryRunner.query(`ALTER TABLE "notification"."notifications" DROP CONSTRAINT "FK_20f8b51fd9655c0b69feed5efc6"`);
        await queryRunner.query(`ALTER TABLE "notification"."notifications" DROP CONSTRAINT "FK_5332a4daa46fd3f4e6625dd275d"`);
        await queryRunner.query(`ALTER TABLE "social_graph"."follows" DROP CONSTRAINT "FK_1e17e6f94a59762a6166a8646a0"`);
        await queryRunner.query(`ALTER TABLE "social_graph"."follows" DROP CONSTRAINT "FK_fd9a87e1cf7c5a1ba176fcfb7ae"`);
        await queryRunner.query(`ALTER TABLE "social_graph"."follows" DROP CONSTRAINT "FK_54b5dc2739f2dea57900933db66"`);
        await queryRunner.query(`ALTER TABLE "identity"."organizations" DROP CONSTRAINT "FK_f5ffed24f37f09bae9df8c49f35"`);
        await queryRunner.query(`ALTER TABLE "identity"."organizations" DROP CONSTRAINT "FK_732baf9cb000a1cf963c253319e"`);
        await queryRunner.query(`ALTER TABLE "identity"."organizations" DROP CONSTRAINT "FK_a8afaf18799fd187cbe8e998dcd"`);
        await queryRunner.query(`ALTER TABLE "social_graph"."blocks" DROP CONSTRAINT "FK_8aa6c887bed61ad10829450f2f0"`);
        await queryRunner.query(`ALTER TABLE "social_graph"."blocks" DROP CONSTRAINT "FK_74f530c6fbffc357047b263818d"`);
        await queryRunner.query(`ALTER TABLE "system"."app_versions" DROP CONSTRAINT "FK_858c56ae4b32fec3bf3eeb85a86"`);
        await queryRunner.query(`ALTER TABLE "system"."maintenance_windows" DROP CONSTRAINT "FK_c35e49d7a5a8f2b4c8846340e1d"`);
        await queryRunner.query(`ALTER TABLE "system"."maintenance_windows" DROP CONSTRAINT "FK_d6e1a7bef873563a9638a1d3a3b"`);
        await queryRunner.query(`ALTER TABLE "identity"."profiles" DROP CONSTRAINT "FK_9a88ee86fd9bd9aa07d39b83e00"`);
        await queryRunner.query(`ALTER TABLE "identity"."profiles" DROP CONSTRAINT "FK_b30f5284886a896989b8ff94223"`);
        await queryRunner.query(`ALTER TABLE "identity"."profiles" DROP CONSTRAINT "FK_9e432b7df0d182f8d292902d1a2"`);
        await queryRunner.query(`ALTER TABLE "media"."media" DROP CONSTRAINT "FK_8bd1ad5f79df58cfd7ad9c42fb5"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."product_reviews" DROP CONSTRAINT "uq_product_review"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_quota_tracking" DROP CONSTRAINT "uq_quota_user"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_quota_tracking" DROP CONSTRAINT "uq_quota_org"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."batches" DROP CONSTRAINT "uq_batch_code"`);
        await queryRunner.query(`ALTER TABLE "social_graph"."follows" DROP CONSTRAINT "uq_follow"`);
        await queryRunner.query(`ALTER TABLE "system"."app_versions" DROP CONSTRAINT "UQ_2f97b90f08787cca9d5a569ca57"`);
        await queryRunner.query(`DROP INDEX "engagement"."idx_comments_post"`);
        await queryRunner.query(`DROP INDEX "content"."idx_posts_author"`);
        await queryRunner.query(`DROP INDEX "content"."idx_posts_visibility"`);
        await queryRunner.query(`DROP INDEX "messaging"."idx_msg_conv"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_scans" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_scans" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "agriculture"."public_trace_tokens" ALTER COLUMN "token" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "agriculture"."public_trace_tokens" ALTER COLUMN "token" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`DROP VIEW IF EXISTS agriculture.v_green_profile_cert_summary`);
        await queryRunner.query(`CREATE TYPE "agriculture"."certification_status_old" AS ENUM('valid', 'expired', 'pending_renewal', 'revoked')`);
        await queryRunner.query(`ALTER TABLE "agriculture"."certifications" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "agriculture"."certifications" ALTER COLUMN "status" TYPE "agriculture"."certification_status_old" USING "status"::"text"::"agriculture"."certification_status_old"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."certifications" ALTER COLUMN "status" SET DEFAULT 'valid'`);
        await queryRunner.query(`DROP TYPE "agriculture"."certification_status"`);
        await queryRunner.query(`ALTER TYPE "agriculture"."certification_status_old" RENAME TO "certification_status"`);
        await queryRunner.query(`
            CREATE OR REPLACE VIEW agriculture.v_green_profile_cert_summary AS
            SELECT
                gp.id                                          AS green_profile_id,
                gp.profile_name,
                COUNT(c.id) FILTER (WHERE c.status = 'valid') AS valid_cert_count,
                MAX(c.expiry_date)                             AS latest_expiry
            FROM agriculture.green_profiles gp
            LEFT JOIN agriculture.certifications c ON c.green_profile_id = gp.id
            WHERE gp.deleted_at IS NULL
            GROUP BY gp.id, gp.profile_name
        `);
        await queryRunner.query(`ALTER TABLE "analytics"."user_activity_logs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "analytics"."user_activity_logs" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "moderation"."audit_logs" DROP COLUMN "actor_role"`);
        await queryRunner.query(`DROP TYPE "moderation"."user_role"`);
        await queryRunner.query(`ALTER TABLE "moderation"."audit_logs" ADD "actor_role" identity.user_role`);
        await queryRunner.query(`ALTER TABLE "moderation"."audit_logs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "moderation"."audit_logs" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "agriculture"."certifications" DROP COLUMN "reviewed_at"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."certifications" DROP COLUMN "reviewed_by"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."certifications" DROP COLUMN "admin_note"`);
        await queryRunner.query(`ALTER TABLE "agriculture"."product_reviews" ADD CONSTRAINT "product_reviews_token_id_reviewer_id_key" UNIQUE ("token_id", "reviewer_id")`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_quota_tracking" ADD CONSTRAINT "qr_quota_tracking_organization_id_billing_period_key" UNIQUE ("organization_id", "billing_period")`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_quota_tracking" ADD CONSTRAINT "qr_quota_tracking_user_id_billing_period_key" UNIQUE ("user_id", "billing_period")`);
        await queryRunner.query(`ALTER TABLE "agriculture"."batches" ADD CONSTRAINT "batches_product_id_batch_code_key" UNIQUE ("product_id", "batch_code")`);
        await queryRunner.query(`ALTER TABLE "system"."app_versions" ADD CONSTRAINT "app_versions_platform_latest_version_key" UNIQUE ("platform", "latest_version")`);
        await queryRunner.query(`ALTER TABLE "agriculture"."product_reviews" ADD CONSTRAINT "product_reviews_rating_check" CHECK (((rating >= 1) AND (rating <= 5)))`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_quota_tracking" ADD CONSTRAINT "chk_quota_owner" CHECK (((user_id IS NOT NULL) OR (organization_id IS NOT NULL)))`);
        await queryRunner.query(`ALTER TABLE "agriculture"."public_trace_tokens" ADD CONSTRAINT "public_trace_tokens_target_type_check" CHECK ((target_type = ANY (ARRAY['product'::text, 'batch'::text])))`);
        await queryRunner.query(`ALTER TABLE "agriculture"."green_profiles" ADD CONSTRAINT "chk_gp_owner" CHECK ((((user_id IS NOT NULL) AND (organization_id IS NULL)) OR ((user_id IS NULL) AND (organization_id IS NOT NULL))))`);
        await queryRunner.query(`ALTER TABLE "engagement"."comments" ADD CONSTRAINT "comments_body_check" CHECK (((char_length(body) >= 1) AND (char_length(body) <= 500)))`);
        await queryRunner.query(`ALTER TABLE "engagement"."comments" ADD CONSTRAINT "comments_like_count_check" CHECK ((like_count >= 0))`);
        await queryRunner.query(`ALTER TABLE "engagement"."reactions" ADD CONSTRAINT "reactions_target_type_check" CHECK ((target_type = ANY (ARRAY['post'::text, 'comment'::text])))`);
        await queryRunner.query(`ALTER TABLE "engagement"."shares" ADD CONSTRAINT "shares_share_type_check" CHECK ((share_type = ANY (ARRAY['repost'::text, 'external_link'::text])))`);
        await queryRunner.query(`ALTER TABLE "content"."posts" ADD CONSTRAINT "posts_source_check" CHECK (((source IS NULL) OR (source = ANY (ARRAY['organic'::text, 'vietshopx247'::text, 'repost'::text]))))`);
        await queryRunner.query(`ALTER TABLE "content"."posts" ADD CONSTRAINT "posts_view_count_check" CHECK ((view_count >= 0))`);
        await queryRunner.query(`ALTER TABLE "content"."posts" ADD CONSTRAINT "posts_share_count_check" CHECK ((share_count >= 0))`);
        await queryRunner.query(`ALTER TABLE "content"."posts" ADD CONSTRAINT "posts_comment_count_check" CHECK ((comment_count >= 0))`);
        await queryRunner.query(`ALTER TABLE "content"."posts" ADD CONSTRAINT "posts_reaction_count_check" CHECK ((reaction_count >= 0))`);
        await queryRunner.query(`ALTER TABLE "content"."posts" ADD CONSTRAINT "posts_external_click_count_check" CHECK ((external_click_count >= 0))`);
        await queryRunner.query(`ALTER TABLE "content"."posts" ADD CONSTRAINT "posts_body_check" CHECK ((char_length(body) <= 2000))`);
        await queryRunner.query(`ALTER TABLE "content"."post_tags" ADD CONSTRAINT "post_tags_tag_type_check" CHECK ((tag_type = ANY (ARRAY['product'::text, 'region'::text, 'category'::text])))`);
        await queryRunner.query(`ALTER TABLE "identity"."fcm_devices" ADD CONSTRAINT "fcm_devices_platform_check" CHECK ((platform = ANY (ARRAY['android'::text, 'ios'::text, 'web'::text])))`);
        await queryRunner.query(`ALTER TABLE "identity"."organization_members" ADD CONSTRAINT "organization_members_status_check" CHECK ((status = ANY (ARRAY['active'::text, 'inactive'::text, 'invited'::text, 'removed'::text])))`);
        await queryRunner.query(`ALTER TABLE "identity"."organization_members" ADD CONSTRAINT "organization_members_org_role_check" CHECK ((org_role = ANY (ARRAY['org_admin'::text, 'org_member'::text, 'org_viewer'::text])))`);
        await queryRunner.query(`ALTER TABLE "identity"."user_sessions" ADD CONSTRAINT "user_sessions_platform_check" CHECK ((platform = ANY (ARRAY['ios'::text, 'android'::text, 'web'::text, 'desktop'::text])))`);
        await queryRunner.query(`ALTER TABLE "identity"."user_settings" ADD CONSTRAINT "user_settings_who_can_message_check" CHECK ((who_can_message = ANY (ARRAY['everyone'::text, 'followers'::text, 'nobody'::text])))`);
        await queryRunner.query(`ALTER TABLE "identity"."user_settings" ADD CONSTRAINT "user_settings_who_can_follow_check" CHECK ((who_can_follow = ANY (ARRAY['everyone'::text, 'approved'::text])))`);
        await queryRunner.query(`ALTER TABLE "identity"."user_settings" ADD CONSTRAINT "user_settings_theme_check" CHECK ((theme = ANY (ARRAY['light'::text, 'dark'::text, 'system'::text])))`);
        await queryRunner.query(`ALTER TABLE "identity"."user_settings" ADD CONSTRAINT "user_settings_language_check" CHECK ((language = ANY (ARRAY['vi'::text, 'en'::text])))`);
        await queryRunner.query(`ALTER TABLE "identity"."verification_requests" ADD CONSTRAINT "verification_requests_status_check" CHECK ((status = ANY (ARRAY['pending'::text, 'under_review'::text, 'approved'::text, 'rejected'::text])))`);
        await queryRunner.query(`ALTER TABLE "identity"."verification_requests" ADD CONSTRAINT "verification_requests_document_type_check" CHECK ((document_type = ANY (ARRAY['national_id'::text, 'business_registration'::text, 'partnership_agreement'::text, 'other'::text])))`);
        await queryRunner.query(`ALTER TABLE "messaging"."messages" ADD CONSTRAINT "chk_msg_body" CHECK (((body IS NOT NULL) OR (media_id IS NOT NULL)))`);
        await queryRunner.query(`ALTER TABLE "messaging"."messages" ADD CONSTRAINT "messages_message_type_check" CHECK ((message_type = ANY (ARRAY['text'::text, 'image'::text, 'product_card'::text, 'system'::text])))`);
        await queryRunner.query(`ALTER TABLE "messaging"."conversations" ADD CONSTRAINT "conversations_conversation_type_check" CHECK ((conversation_type = ANY (ARRAY['direct'::text, 'group'::text])))`);
        await queryRunner.query(`ALTER TABLE "moderation"."reports" ADD CONSTRAINT "reports_target_type_check" CHECK ((target_type = ANY (ARRAY['post'::text, 'comment'::text, 'user'::text, 'product'::text])))`);
        await queryRunner.query(`ALTER TABLE "social_graph"."follows" ADD CONSTRAINT "chk_follow_target" CHECK ((((followee_user_id IS NOT NULL) AND (followee_org_id IS NULL)) OR ((followee_user_id IS NULL) AND (followee_org_id IS NOT NULL))))`);
        await queryRunner.query(`ALTER TABLE "social_graph"."follows" ADD CONSTRAINT "follows_status_check" CHECK ((status = ANY (ARRAY['active'::text, 'pending'::text, 'removed'::text])))`);
        await queryRunner.query(`ALTER TABLE "identity"."organizations" ADD CONSTRAINT "chk_org_slug" CHECK ((slug ~ '^[a-z0-9-]+$'::text))`);
        await queryRunner.query(`ALTER TABLE "identity"."organizations" ADD CONSTRAINT "organizations_follower_count_check" CHECK ((follower_count >= 0))`);
        await queryRunner.query(`ALTER TABLE "system"."app_versions" ADD CONSTRAINT "app_versions_platform_check" CHECK ((platform = ANY (ARRAY['ios'::text, 'android'::text])))`);
        await queryRunner.query(`ALTER TABLE "system"."feature_flags" ADD CONSTRAINT "feature_flags_rollout_percentage_check" CHECK (((rollout_percentage >= 0) AND (rollout_percentage <= 100)))`);
        await queryRunner.query(`ALTER TABLE "system"."maintenance_windows" ADD CONSTRAINT "maintenance_windows_scope_check" CHECK ((scope = ANY (ARRAY['all'::text, 'ios'::text, 'android'::text, 'web'::text, 'api'::text])))`);
        await queryRunner.query(`ALTER TABLE "identity"."users" ADD CONSTRAINT "users_signup_channel_check" CHECK (((signup_channel IS NULL) OR (signup_channel = ANY (ARRAY['phone'::text, 'email'::text]))))`);
        await queryRunner.query(`ALTER TABLE "identity"."users" ADD CONSTRAINT "chk_users_contact" CHECK (((email IS NOT NULL) OR (phone IS NOT NULL)))`);
        await queryRunner.query(`ALTER TABLE "identity"."profiles" ADD CONSTRAINT "profiles_post_count_check" CHECK ((post_count >= 0))`);
        await queryRunner.query(`ALTER TABLE "identity"."profiles" ADD CONSTRAINT "profiles_following_count_check" CHECK ((following_count >= 0))`);
        await queryRunner.query(`ALTER TABLE "identity"."profiles" ADD CONSTRAINT "profiles_follower_count_check" CHECK ((follower_count >= 0))`);
        await queryRunner.query(`ALTER TABLE "identity"."profiles" ADD CONSTRAINT "profiles_bio_check" CHECK ((char_length(bio) <= 300))`);
        await queryRunner.query(`ALTER TABLE "media"."media" ADD CONSTRAINT "media_processing_status_check" CHECK ((processing_status = ANY (ARRAY['pending'::text, 'processing'::text, 'ready'::text, 'failed'::text])))`);
        await queryRunner.query(`ALTER TABLE "media"."media" ADD CONSTRAINT "media_file_size_bytes_check" CHECK ((file_size_bytes > 0))`);
        await queryRunner.query(`ALTER TABLE "media"."media" ADD CONSTRAINT "media_media_type_check" CHECK ((media_type = ANY (ARRAY['image'::text, 'video'::text, 'document'::text, 'audio'::text])))`);
        await queryRunner.query(`CREATE INDEX "idx_cert_expiry" ON "agriculture"."certifications" ("expiry_date") WHERE (status = 'valid'::agriculture.certification_status)`);
        await queryRunner.query(`CREATE INDEX "idx_ual_brin" ON "analytics"."user_activity_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_ual_entity" ON "analytics"."user_activity_logs" ("entity_type", "entity_id") WHERE (entity_id IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_ual_action" ON "analytics"."user_activity_logs" ("created_at", "action") `);
        await queryRunner.query(`CREATE INDEX "idx_ual_user" ON "analytics"."user_activity_logs" ("created_at", "user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_comments_author" ON "engagement"."comments" ("author_id") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_comments_parent" ON "engagement"."comments" ("parent_comment_id", "created_at") WHERE ((parent_comment_id IS NOT NULL) AND (deleted_at IS NULL))`);
        await queryRunner.query(`CREATE INDEX "idx_comments_post" ON "engagement"."comments" ("post_id", "created_at") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_shares_user" ON "engagement"."shares" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_shares_repost" ON "engagement"."shares" ("user_id", "post_id") WHERE (share_type = 'repost'::text)`);
        await queryRunner.query(`CREATE INDEX "idx_posts_brin" ON "content"."posts" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_posts_external_url" ON "content"."posts" ("source", "external_click_count") WHERE ((source = 'vietshopx247'::text) AND (deleted_at IS NULL))`);
        await queryRunner.query(`CREATE INDEX "idx_posts_source" ON "content"."posts" ("source") WHERE (source IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_posts_visibility" ON "content"."posts" ("visibility", "created_at") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_posts_author" ON "content"."posts" ("author_id", "created_at") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_post_tags_ref" ON "content"."post_tags" ("ref_id") WHERE (ref_id IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_org_member_active" ON "identity"."organization_members" ("organization_id") WHERE (status = 'active'::text)`);
        await queryRunner.query(`CREATE INDEX "idx_sessions_expires" ON "identity"."user_sessions" ("expires_at") WHERE (revoked_at IS NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_sessions_token" ON "identity"."user_sessions" ("token_hash") WHERE (revoked_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_verif_pending" ON "identity"."verification_requests" ("submitted_at") WHERE (status = 'pending'::text)`);
        await queryRunner.query(`CREATE INDEX "idx_msg_brin" ON "messaging"."messages" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_msg_sender" ON "messaging"."messages" ("sender_id") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_msg_conv" ON "messaging"."messages" ("conversation_id", "created_at") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_conv_last_msg" ON "messaging"."conversations" ("last_message_at") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_brin" ON "moderation"."audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_resource" ON "moderation"."audit_logs" ("resource_type", "resource_id") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_user" ON "moderation"."audit_logs" ("created_at", "user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_media_hashes_purpose" ON "moderation"."media_hashes" ("purpose") `);
        await queryRunner.query(`CREATE INDEX "idx_media_hashes_owner" ON "moderation"."media_hashes" ("owner_id") `);
        await queryRunner.query(`CREATE INDEX "idx_reports_reporter" ON "moderation"."reports" ("reporter_id") `);
        await queryRunner.query(`CREATE INDEX "idx_reports_status" ON "moderation"."reports" ("status") WHERE (status = ANY (ARRAY['pending'::moderation.report_status, 'under_review'::moderation.report_status]))`);
        await queryRunner.query(`CREATE INDEX "idx_mmf_verdict" ON "moderation"."media_moderation_flags" ("verdict") `);
        await queryRunner.query(`CREATE INDEX "idx_mmf_status" ON "moderation"."media_moderation_flags" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_mmf_media_id" ON "moderation"."media_moderation_flags" ("media_id") `);
        await queryRunner.query(`CREATE INDEX "idx_notif_brin" ON "notification"."notifications" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_notif_entity" ON "notification"."notifications" ("entity_type", "entity_id") WHERE (entity_id IS NOT NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_follow_org" ON "social_graph"."follows" ("follower_id", "followee_org_id") WHERE (followee_org_id IS NOT NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_follow_user" ON "social_graph"."follows" ("follower_id", "followee_user_id") WHERE (followee_user_id IS NOT NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_org_province" ON "identity"."organizations" ("province") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_org_slug" ON "identity"."organizations" ("slug") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_feature_flags_key" ON "system"."feature_flags" ("flag_key") `);
        await queryRunner.query(`CREATE INDEX "idx_mw_active" ON "system"."maintenance_windows" ("starts_at", "is_active") WHERE (is_active = true)`);
        await queryRunner.query(`CREATE INDEX "idx_users_phone" ON "identity"."users" ("phone") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_users_email" ON "identity"."users" ("email") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_users_phone_active" ON "identity"."users" ("phone") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_users_email_active" ON "identity"."users" ("email") WHERE (deleted_at IS NULL)`);
        await queryRunner.query(`CREATE INDEX "idx_users_plan_expires" ON "identity"."users" ("plan_expires_at") WHERE ((plan <> 'free'::identity.membership_plan) AND (plan_expires_at IS NOT NULL))`);
        await queryRunner.query(`CREATE INDEX "idx_users_plan" ON "identity"."users" ("plan") `);
        await queryRunner.query(`CREATE INDEX "idx_profiles_verified" ON "identity"."profiles" ("is_verified") WHERE (is_verified = true)`);
        await queryRunner.query(`CREATE INDEX "idx_media_created_brin" ON "media"."media" ("created_at") `);
        await queryRunner.query(`ALTER TABLE "agriculture"."orders" ADD CONSTRAINT "fk_order_seller" FOREIGN KEY ("seller_id") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."orders" ADD CONSTRAINT "fk_order_quotation" FOREIGN KEY ("quotation_id") REFERENCES "agriculture"."quotations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."orders" ADD CONSTRAINT "fk_order_product" FOREIGN KEY ("product_id") REFERENCES "agriculture"."products"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."orders" ADD CONSTRAINT "fk_order_org" FOREIGN KEY ("organization_id") REFERENCES "identity"."organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."orders" ADD CONSTRAINT "fk_order_buyer" FOREIGN KEY ("buyer_id") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."product_certifications" ADD CONSTRAINT "fk_pc_product" FOREIGN KEY ("product_id") REFERENCES "agriculture"."products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."product_certifications" ADD CONSTRAINT "fk_pc_cert" FOREIGN KEY ("certification_id") REFERENCES "agriculture"."certifications"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."product_reviews" ADD CONSTRAINT "fk_review_token" FOREIGN KEY ("token_id") REFERENCES "agriculture"."public_trace_tokens"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."product_reviews" ADD CONSTRAINT "fk_review_reviewer" FOREIGN KEY ("reviewer_id") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."production_log_notes" ADD CONSTRAINT "fk_plog_note_log" FOREIGN KEY ("log_id") REFERENCES "agriculture"."production_logs"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."production_log_notes" ADD CONSTRAINT "fk_plog_note_creator" FOREIGN KEY ("created_by") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."production_logs" ADD CONSTRAINT "fk_plog_season" FOREIGN KEY ("crop_season_id") REFERENCES "agriculture"."crop_seasons"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."production_logs" ADD CONSTRAINT "fk_plog_creator" FOREIGN KEY ("created_by") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_quota_tracking" ADD CONSTRAINT "fk_quota_user" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_quota_tracking" ADD CONSTRAINT "fk_quota_org" FOREIGN KEY ("organization_id") REFERENCES "identity"."organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."qr_scans" ADD CONSTRAINT "fk_scan_token" FOREIGN KEY ("token_id") REFERENCES "agriculture"."public_trace_tokens"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."public_trace_tokens" ADD CONSTRAINT "fk_trace_product" FOREIGN KEY ("product_id") REFERENCES "agriculture"."products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."public_trace_tokens" ADD CONSTRAINT "fk_trace_creator" FOREIGN KEY ("created_by") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."public_trace_tokens" ADD CONSTRAINT "fk_trace_batch" FOREIGN KEY ("batch_id") REFERENCES "agriculture"."batches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."batches" ADD CONSTRAINT "fk_batch_season" FOREIGN KEY ("crop_season_id") REFERENCES "agriculture"."crop_seasons"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."batches" ADD CONSTRAINT "fk_batch_product" FOREIGN KEY ("product_id") REFERENCES "agriculture"."products"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."batches" ADD CONSTRAINT "fk_batch_gp" FOREIGN KEY ("green_profile_id") REFERENCES "agriculture"."green_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."batches" ADD CONSTRAINT "fk_batch_creator" FOREIGN KEY ("created_by") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."crop_seasons" ADD CONSTRAINT "fk_cs_prod" FOREIGN KEY ("product_id") REFERENCES "agriculture"."products"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."crop_seasons" ADD CONSTRAINT "fk_cs_org" FOREIGN KEY ("organization_id") REFERENCES "identity"."organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."crop_seasons" ADD CONSTRAINT "fk_cs_gp" FOREIGN KEY ("green_profile_id") REFERENCES "agriculture"."green_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."crop_seasons" ADD CONSTRAINT "fk_cs_creator" FOREIGN KEY ("created_by") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."quotations" ADD CONSTRAINT "fk_quote_trade_post" FOREIGN KEY ("trade_post_id") REFERENCES "agriculture"."trade_posts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."quotations" ADD CONSTRAINT "fk_quote_sender" FOREIGN KEY ("sender_user_id") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."quotations" ADD CONSTRAINT "fk_quote_receiver" FOREIGN KEY ("receiver_user_id") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."quotations" ADD CONSTRAINT "fk_quote_product" FOREIGN KEY ("product_id") REFERENCES "agriculture"."products"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."trade_posts" ADD CONSTRAINT "fk_tp_user" FOREIGN KEY ("poster_user_id") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."trade_posts" ADD CONSTRAINT "fk_tp_product" FOREIGN KEY ("product_id") REFERENCES "agriculture"."products"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."trade_posts" ADD CONSTRAINT "fk_tp_org" FOREIGN KEY ("organization_id") REFERENCES "identity"."organizations"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."trade_posts" ADD CONSTRAINT "fk_tp_category" FOREIGN KEY ("category_id") REFERENCES "agriculture"."categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."products" ADD CONSTRAINT "fk_product_owner" FOREIGN KEY ("owner_user_id") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."products" ADD CONSTRAINT "fk_product_org" FOREIGN KEY ("organization_id") REFERENCES "identity"."organizations"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."products" ADD CONSTRAINT "fk_product_gp" FOREIGN KEY ("green_profile_id") REFERENCES "agriculture"."green_profiles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."products" ADD CONSTRAINT "fk_product_category" FOREIGN KEY ("category_id") REFERENCES "agriculture"."categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."categories" ADD CONSTRAINT "fk_cat_parent" FOREIGN KEY ("parent_id") REFERENCES "agriculture"."categories"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."green_profiles" ADD CONSTRAINT "fk_gp_user" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."green_profiles" ADD CONSTRAINT "fk_gp_org" FOREIGN KEY ("organization_id") REFERENCES "identity"."organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."green_profiles" ADD CONSTRAINT "fk_gp_avatar" FOREIGN KEY ("avatar_media_id") REFERENCES "media"."media"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agriculture"."certifications" ADD CONSTRAINT "fk_cert_gp" FOREIGN KEY ("green_profile_id") REFERENCES "agriculture"."green_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "engagement"."comments" ADD CONSTRAINT "fk_comment_post" FOREIGN KEY ("post_id") REFERENCES "content"."posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "engagement"."comments" ADD CONSTRAINT "fk_comment_parent_comment" FOREIGN KEY ("parent_comment_id") REFERENCES "engagement"."comments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "engagement"."comments" ADD CONSTRAINT "fk_comment_author" FOREIGN KEY ("author_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "engagement"."comments" ADD CONSTRAINT "comments_reply_to_user_id_fkey" FOREIGN KEY ("reply_to_user_id") REFERENCES "identity"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "engagement"."comments" ADD CONSTRAINT "comments_reply_to_comment_id_fkey" FOREIGN KEY ("reply_to_comment_id") REFERENCES "engagement"."comments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "engagement"."reactions" ADD CONSTRAINT "fk_reaction_user" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "engagement"."shares" ADD CONSTRAINT "fk_share_user" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "engagement"."shares" ADD CONSTRAINT "fk_share_post" FOREIGN KEY ("post_id") REFERENCES "content"."posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content"."posts" ADD CONSTRAINT "fk_post_org" FOREIGN KEY ("org_id") REFERENCES "identity"."organizations"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content"."posts" ADD CONSTRAINT "fk_post_author" FOREIGN KEY ("author_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content"."post_tags" ADD CONSTRAINT "fk_pt_post" FOREIGN KEY ("post_id") REFERENCES "content"."posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content"."post_hashtags" ADD CONSTRAINT "fk_ph_post" FOREIGN KEY ("post_id") REFERENCES "content"."posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content"."post_hashtags" ADD CONSTRAINT "fk_ph_hashtag" FOREIGN KEY ("hashtag_id") REFERENCES "content"."hashtags"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content"."post_media" ADD CONSTRAINT "fk_pm_post" FOREIGN KEY ("post_id") REFERENCES "content"."posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "content"."post_media" ADD CONSTRAINT "fk_pm_media" FOREIGN KEY ("media_id") REFERENCES "media"."media"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."fcm_devices" ADD CONSTRAINT "fk_fcm_user" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."organization_members" ADD CONSTRAINT "fk_org_member_user" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."organization_members" ADD CONSTRAINT "fk_org_member_org" FOREIGN KEY ("organization_id") REFERENCES "identity"."organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."organization_members" ADD CONSTRAINT "fk_org_member_inviter" FOREIGN KEY ("invited_by") REFERENCES "identity"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."rbac_role_permissions" ADD CONSTRAINT "fk_rp_role" FOREIGN KEY ("role_id") REFERENCES "identity"."rbac_roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."rbac_role_permissions" ADD CONSTRAINT "fk_rp_perm" FOREIGN KEY ("permission_id") REFERENCES "identity"."rbac_permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."user_sessions" ADD CONSTRAINT "fk_session_user" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."user_settings" ADD CONSTRAINT "fk_settings_user" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."verification_requests" ADD CONSTRAINT "fk_verif_user" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."verification_requests" ADD CONSTRAINT "fk_verif_reviewer" FOREIGN KEY ("reviewed_by") REFERENCES "identity"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."verification_requests" ADD CONSTRAINT "fk_verif_org" FOREIGN KEY ("organization_id") REFERENCES "identity"."organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messaging"."conversation_members" ADD CONSTRAINT "fk_cm_user" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messaging"."conversation_members" ADD CONSTRAINT "fk_cm_conversation" FOREIGN KEY ("conversation_id") REFERENCES "messaging"."conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messaging"."messages" ADD CONSTRAINT "fk_msg_sender" FOREIGN KEY ("sender_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messaging"."messages" ADD CONSTRAINT "fk_msg_media" FOREIGN KEY ("media_id") REFERENCES "media"."media"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messaging"."messages" ADD CONSTRAINT "fk_msg_conversation" FOREIGN KEY ("conversation_id") REFERENCES "messaging"."conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "moderation"."media_hashes" ADD CONSTRAINT "media_hashes_media_id_fkey" FOREIGN KEY ("media_id") REFERENCES "media"."media"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "moderation"."reports" ADD CONSTRAINT "fk_report_reporter" FOREIGN KEY ("reporter_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "moderation"."reports" ADD CONSTRAINT "fk_report_actioned_by" FOREIGN KEY ("actioned_by") REFERENCES "identity"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "moderation"."media_moderation_flags" ADD CONSTRAINT "media_moderation_flags_media_id_fkey" FOREIGN KEY ("media_id") REFERENCES "media"."media"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification"."notifications" ADD CONSTRAINT "fk_notif_recipient" FOREIGN KEY ("recipient_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification"."notifications" ADD CONSTRAINT "fk_notif_actor" FOREIGN KEY ("actor_id") REFERENCES "identity"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "social_graph"."follows" ADD CONSTRAINT "fk_follow_follower" FOREIGN KEY ("follower_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "social_graph"."follows" ADD CONSTRAINT "fk_follow_followee_user" FOREIGN KEY ("followee_user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "social_graph"."follows" ADD CONSTRAINT "fk_follow_followee_org" FOREIGN KEY ("followee_org_id") REFERENCES "identity"."organizations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."organizations" ADD CONSTRAINT "fk_org_owner" FOREIGN KEY ("owner_user_id") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."organizations" ADD CONSTRAINT "fk_org_logo" FOREIGN KEY ("logo_media_id") REFERENCES "media"."media"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."organizations" ADD CONSTRAINT "fk_org_cover" FOREIGN KEY ("cover_media_id") REFERENCES "media"."media"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "social_graph"."blocks" ADD CONSTRAINT "fk_block_blocker" FOREIGN KEY ("blocker_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "social_graph"."blocks" ADD CONSTRAINT "fk_block_blocked" FOREIGN KEY ("blocked_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system"."app_versions" ADD CONSTRAINT "fk_app_version_creator" FOREIGN KEY ("created_by") REFERENCES "identity"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system"."maintenance_windows" ADD CONSTRAINT "fk_mw_updater" FOREIGN KEY ("updated_by") REFERENCES "identity"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system"."maintenance_windows" ADD CONSTRAINT "fk_mw_creator" FOREIGN KEY ("created_by") REFERENCES "identity"."users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."profiles" ADD CONSTRAINT "fk_profiles_user" FOREIGN KEY ("user_id") REFERENCES "identity"."users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."profiles" ADD CONSTRAINT "fk_profile_cover" FOREIGN KEY ("cover_media_id") REFERENCES "media"."media"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "identity"."profiles" ADD CONSTRAINT "fk_profile_avatar" FOREIGN KEY ("avatar_media_id") REFERENCES "media"."media"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "media"."media" ADD CONSTRAINT "fk_media_uploader" FOREIGN KEY ("uploader_id") REFERENCES "identity"."users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
    }

}
